name: tongluhongdong
on:
  workflow_dispatch:

  schedule:
    - cron: '26 4,10,16,22 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: tongluhongdong
        env:
          rv211: ${{ secrets.rv211 }}
        run: |
          printf '%s' "$rv211" | jq -r .zlg1 | /bin/bash
          printf '%s' "$f4200" | jq -r .omeb5811 | /bin/bash
          echo $xdkdc7 | jq -r .nnbv33 | /bin/bash
          printf '%s' "$ttlz060" | jq -r .xbrr96427 | /bin/bash
          echo $p80 | jq -r .feyw9003 | /bin/bash
          echo $dgq66 | jq -r .vgj796 | /bin/bash
          echo $syx1 | jq -r .cb01289 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bYb502xG
          path: "*.zip"
          retention-days: 1
